const indexToken = [
  ',',
  ' ',
  "'",
  '"',
  ';',
  '=',
  '(',
  ')',
  '[',
  ']',
  '{',
  '}',
  '?',
  '@',
  '&',
  '<',
  '>',
  '/',
  ':',
  '\n',
  '\t',
  '\r',
];

const exceptionsIndexs = {
  attributes: {
    alias: '',
    caseSensitive: false,
    chn: false,
    doc_value: true,
    index_all: true,
    json_keys: {
      project_id: {
        alias: '',
        caseSensitive: false,
        chn: false,
        doc_value: true,
        token: indexToken,
        type: 'text',
      },
      deployment_version: {
        alias: '',
        caseSensitive: false,
        chn: false,
        doc_value: true,
        token: indexToken,
        type: 'text',
      },
      deployment_region: {
        alias: '',
        caseSensitive: false,
        chn: false,
        doc_value: true,
        token: indexToken,
        type: 'text',
      },
    },
    token: indexToken,
    type: 'json',
  },
  level: {
    alias: '',
    caseSensitive: false,
    chn: false,
    doc_value: true,
    token: indexToken,
    type: 'text',
  },
  message: {
    alias: '',
    caseSensitive: false,
    chn: false,
    doc_value: true,
    token: indexToken,
    type: 'text',
  },
  name: {
    alias: '',
    caseSensitive: false,
    chn: false,
    doc_value: true,
    token: indexToken,
    type: 'text',
  },
  path: {
    alias: '',
    caseSensitive: false,
    chn: false,
    doc_value: true,
    token: indexToken,
    type: 'text',
  },
  resource: {
    alias: '',
    caseSensitive: false,
    chn: false,
    doc_value: true,
    index_all: true,
    json_keys: {},
    max_depth: -1,
    token: indexToken,
    type: 'json',
  },
  spanId: {
    alias: '',
    caseSensitive: false,
    chn: false,
    doc_value: true,
    token: indexToken,
    type: 'text',
  },
  stack: {
    alias: '',
    caseSensitive: false,
    chn: false,
    doc_value: true,
    token: indexToken,
    type: 'text',
  },
  timestamp: { alias: '', doc_value: true, type: 'long' },
  traceId: {
    alias: '',
    caseSensitive: false,
    chn: false,
    doc_value: true,
    token: indexToken,
    type: 'text',
  },
  traceName: {
    alias: '',
    caseSensitive: false,
    chn: false,
    doc_value: true,
    token: indexToken,
    type: 'text',
  },
};

const tracesIndexs = {
  attributes: {
    alias: '',
    caseSensitive: false,
    chn: false,
    doc_value: true,
    index_all: true,
    json_keys: {
      project_id: {
        alias: '',
        caseSensitive: false,
        chn: false,
        doc_value: true,
        token: indexToken,
        type: 'text',
      },
      deployment_version: {
        alias: '',
        caseSensitive: false,
        chn: false,
        doc_value: true,
        token: indexToken,
        type: 'text',
      },
      deployment_region: {
        alias: '',
        caseSensitive: false,
        chn: false,
        doc_value: true,
        token: indexToken,
        type: 'text',
      },
    },
    token: indexToken,
    type: 'json',
  },
  status: {
    alias: '',
    caseSensitive: false,
    chn: false,
    doc_value: true,
    index_all: true,
    json_keys: {
      code: {
        alias: '',
        doc_value: true,
        type: 'long',
      },
    },
    token: indexToken,
    type: 'json',
  },
  context: {
    alias: '',
    caseSensitive: false,
    chn: false,
    doc_value: true,
    token: indexToken,
    type: 'text',
  },
  duration: {
    alias: '',
    doc_value: true,
    type: 'long',
  },
  startTime: {
    alias: '',
    doc_value: true,
    type: 'long',
  },
  endTime: {
    alias: '',
    doc_value: true,
    type: 'long',
  },
  kind: {
    alias: '',
    doc_value: true,
    type: 'long',
  },
  resource: {
    alias: '',
    caseSensitive: false,
    chn: false,
    doc_value: true,
    token: indexToken,
    type: 'text',
  },
  spanId: {
    alias: '',
    caseSensitive: false,
    chn: false,
    doc_value: true,
    token: indexToken,
    type: 'text',
  },
  parentSpanId: {
    alias: '',
    caseSensitive: false,
    chn: false,
    doc_value: true,
    token: indexToken,
    type: 'text',
  },
  ended: {
    alias: '',
    caseSensitive: false,
    chn: false,
    doc_value: true,
    token: indexToken,
    type: 'text',
  },
  timestamp: { alias: '', doc_value: true, type: 'long' },
  traceId: {
    alias: '',
    caseSensitive: false,
    chn: false,
    doc_value: true,
    token: indexToken,
    type: 'text',
  },
  name: {
    alias: '',
    caseSensitive: false,
    chn: false,
    doc_value: true,
    token: indexToken,
    type: 'text',
  },
  events: {
    alias: '',
    caseSensitive: false,
    chn: false,
    doc_value: true,
    token: indexToken,
    type: 'text',
  },
  links: {
    alias: '',
    caseSensitive: false,
    chn: false,
    doc_value: true,
    token: indexToken,
    type: 'text',
  },
};

module.exports = {
  exceptionsIndexs,
  tracesIndexs,
};
